apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: dad-group-5
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      priorityClassName: high-priority
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            # MUDANÇA CRÍTICA: Definir a password explicitamente para 'root'
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "project"
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "384Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: dad-group-5
spec:
  ports:
    - port: 3306
  selector:
    app: mysql