apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
  namespace: dad-group-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      priorityClassName: low-priority
      containers:
        - name: ws
          image: registry-172.22.21.115.sslip.io/dad-group-5/ws:v2.0.89
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "32Mi"
              cpu: "51m"
            limits:
              memory: "128Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: websocket-server
  namespace: dad-group-5
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: websocket-server